### ISSUE TITLE
Starting at os.pardir vs. at os.path.expanduser('~/Documents')

### ISSUE THREAD

**Issue by cclauss** [Ivoah/WebIDE#4]
More a question than an issue...  The current code allows the user to edit files a the current parent directory (../) and below.  Would it be useful to allow the user to edit **all** Pythonista files or are there performance or security reasons not to do so?

**Comment by Ivoah** [comment]
I chose `../` because I intended the WebIDE folder to be at the documents root, so it would be able to see everything. I didn't know that Pythonista changed the home dir, so `os.path.expanduser('~/Documents')` would work fine.
