### ISSUE TITLE
Permission to Distribute Modified Version

### ISSUE THREAD

**Issue by Gerzer** [Ivoah/WebIDE#9]
First of all, I'd like to thank you for creating this indispensable tool. It works like a charm!

To cut to the chase, **I'd like permission to use parts of WebIDE in a Pythonista-based project on which I am working**. I'm building a semi-real-time code-collaboration tool for Pythonista and will release the code on GitHub once I've gotten the basics working. Someone using Pythonista (the "host") will be able to accept edits to their local code from anyone with a web browser to whom they send a particular URL (a "guest"). (The "host" will have to port-forward their router, of course.) I was hoping that I could utilize WebIDE as the "jumping-off point", so to speak, for the web-based editor that "guests" will use.

Due to the fact that this repository does not have a license file, I figured that it would be best to request explicit permission before doing anything else. I'll gladly include an attribution to you if need be.

Would it be okay if I were to go through with this? If so, then I'd like to know what conditions apply, if any at all do.

Thanks!

**Comment by Ivoah** [comment]
Go ahead! I'm glad somebody has found my work useful :)
I'd just want attribution in your README.
Also be sure to tell me when you're done, I'd love to see what you've made.

**Comment by Gerzer** [comment]
Thanks! I'll make sure to let you know when it's finished. Are a link to this repository and a link to your GitHub profile in the README sufficient?

**Comment by Ivoah** [comment]
Just my name, link to GH profile, and link to this repo should be fine.

**Comment by Gerzer** [comment]
Will do.

(Also, that was one insanely quick reply!)
